### ISSUE TITLE
can't read state ?!

### ISSUE THREAD

**Issue by elpimous** [sinaaghli/moteus_cpp#1]
hello, using your code with my fdcanusb :+1: 
```
#include <moteusapi/MoteusAPI.h>

int main() {
  string dev_name("/dev/ttyACM0");
  int moteus_id = 10;
  MoteusAPI api(dev_name, moteus_id);

  // define a state object
  State curr_state;

  // only read current position
  api.ReadState(curr_state.EN_Position());
  cout << "position: " << curr_state.position << endl;

  // reset the state and only read velocity and torque
  curr_state.Reset();
  api.ReadState(curr_state.EN_Velocity().EN_Torque());

  // read temperature in addition to velocity and torque
  api.ReadState(curr_state.EN_Temp());

  // print everyting
  cout << "velocity: " << curr_state.velocity << endl;
  cout << "torque: " << curr_state.torque << endl;
  cout << "temperature: " << curr_state.temperature << endl;

  return 0;
}
```
I can send commands, make move motor (QDD100 from MJBOTS, ID:10)
but no return state !!
`
predator@predator-Predator-PH317-52:~/moteusapi/example_external/build$ ./positioncmd 
position: nan
velocity: nan
torque: nan
temperature: nan
`
Any idea ?

**Comment by sinaaghli** [comment]
Ups, it doesn't work for me either, not sure how this happened. I'll work on it and let you know once it is fixed!

**Comment by sinaaghli** [comment]
Alright I don't have the complete solution yet but I figured that after power-cycle of moteus board if you first run the tview command
`sudo python3 -m moteus_gui.tview --devices=1`
then close tview and then run the example it will work as expected until the next power cycle.
It seems like tivew is initializing the device once you open which we would need to add those instructions to this library. I'll followup with MJbots to see if they have any guidance with this.

**Comment by sinaaghli** [comment]
@elpimous I think [this](https://github.com/sinaaghli/moteusapi/commit/c3925d2f608424e36bef942111eb0a772b0016f9) fixes the issue, try it out and if you still were having problems feel free to reopen this issue.
